name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2
      - name: install packages
        run: pnpm install
      - name: run test
        run: pnpm test --passWithNoTests
